packages:
    - 'storybook-addon-package' # ← The addon package that gets published to npm
    - 'example-site/shared' # ← shared data and utils
    - 'example-site/react' # ← React demo app
    - 'example-site/svelte' # ← Svelte demo app
onlyBuiltDependencies:
    - esbuild
