export {
	mealDbApi,
	fetchMealById,
	fetchCategories,
	fetchMealsByCategory,
	fetchMealsByArea,
	fetchRandomMealList,
	transformMealData,
	type CategoriesApiResponse,
	type Category,
	type MealDBTransformedResponse,
	type Meal,
	type IngredientMeasurement,
	type MealDBResponse,
	type MealRawData,
} from './mealDbApiUtils'

export {
	generatePaths,
	getFullAddressViaBrackets,
	getFullAddressViaColons,
	getFullAddressViaDollars,
	type AnyRouteAddressStyle,
	type BracketRouteAddress,
	type ColonRouteAddress,
	type DollarRouteAddress,
	type HrefParamName,
	type HrefParams,
	type LinkAddress,
	type RouteAddress,
	type RouteMarks,
} from './routeAddressUtils'
