import type { IconProps } from './iconTypes'
import { Svg } from './Svg'

// <!-- [ldio] SVG content generated by https://loading.io -->

export function LoadingRipples(props: IconProps) {
	return (
		<Svg
			{...props}
			viewBox="0 0 100 100"
			strokeWidth={0}
			width="100"
			height="100"
			style={{ shapeRendering: 'auto', background: 'transparent' }}
		>
			<g>
				<circle
					strokeWidth={2}
					stroke="#000000"
					fill="none"
					r="0"
					cy="50"
					cx="50"
				>
					<animate
						begin="0s"
						values="0;40"
						dur="1s"
						{...{
							calcMode: 'spline',
							keySplines: '0 0.2 0.8 1',
							keyTimes: '0;1',
							repeatCount: 'indefinite',
							attributeName: 'r',
						}}
					/>
					<animate
						begin="0s"
						values="1;0"
						dur="1s"
						{...{
							calcMode: 'spline',
							keySplines: '0.2 0 0.8 1',
							keyTimes: '0;1',
							repeatCount: 'indefinite',
							attributeName: 'opacity',
						}}
					/>
				</circle>
				<circle
					strokeWidth={2}
					stroke="#b0b0b0"
					fill="none"
					r="0"
					cy="50"
					cx="50"
				>
					<animate
						begin="-0.5s"
						values="0;40"
						dur="1s"
						{...{
							calcMode: 'spline',
							keySplines: '0 0.2 0.8 1',
							keyTimes: '0;1',
							repeatCount: 'indefinite',
							attributeName: 'r',
						}}
					/>
					<animate
						begin="-0.5s"
						values="1;0"
						dur="1s"
						{...{
							calcMode: 'spline',
							keySplines: '0.2 0 0.8 1',
							keyTimes: '0;1',
							repeatCount: 'indefinite',
							attributeName: 'opacity',
						}}
					/>
				</circle>
				<g />
			</g>
		</Svg>
	)
}
